<?php
session_start();
require 'PHPMailer/PHPMailerAutoload.php';
if($_SERVER['HTTP_HOST'] == 'localhost'){
	$db_user = "root";			//Enter MySql DB Username
	$db_pass = "";				//Enter MySql DB User Password
	$db_name = "database";	//Enter Mysql DB Name
}
/*

$db_host="localhost";   //mysql host  
$db_user="root";  //databse user name
$db_pass="";  //database password
$db_name="database";  //database name

*/
$tables="*";   // use * for all tables or use , to seperate table names
$email="uma@f5craft.com";     //your email id
///////////////////////////////////////////////////////////////////////////////////////////

/////////don't need to change bellow //////
$return='';
backup($db_host,$db_user,$db_pass,$db_name,$tables,$email);
function backup($db_host,$db_user,$db_pass,$db_name,$tables = '*',$email)
{

  $con= mysql_connect($db_host,$db_user,$db_pass);
  mysql_select_db($db_name,$con);

  //get all of the tables
  if($tables == '*')
  {
    $tables = array();
    $result = mysql_query('SHOW TABLES');
    while($row = mysql_fetch_row($result))
    {
      $tables[] = $row[0];
    }
  }
  else
  {
    $tables = is_array($tables) ? $tables : explode(',',$tables);
  }

  //cycle through
  foreach($tables as $table)
  {
    $result = mysql_query('SELECT * FROM '.$table);
    $num_fields = mysql_num_fields($result);

//    $return.= 'DROP TABLE '.$table.';';
    $row2 = mysql_fetch_row(mysql_query('SHOW CREATE TABLE '.$table));
    $return.= "\n\n".$row2[1].";\n\n";

    for ($i = 0; $i < $num_fields; $i++) 
    {
      while($row = mysql_fetch_row($result))
      {
        $return.= 'INSERT INTO '.$table.' VALUES(';
        for($j=0; $j<$num_fields; $j++) 
        {
          $row[$j] = addslashes($row[$j]);
//          $row[$j] = ereg_replace("\n","\\n",$row[$j]);
          if (isset($row[$j])) { $return.= '"'.$row[$j].'"' ; } else { $return.= '""'; }
          if ($j<($num_fields-1)) { $return.= ','; }
        }
        $return.= ");\n";
      }
    }
    $return.="\n\n\n";
  }

  //save file
  $filename='views/ioi_v2/'.time().'-'.(md5(implode(',',$tables))).'.sql';
  $handle = fopen($filename,'w+');
  fwrite($handle,$return);
  fclose($handle);
  query($filename);
  compress($filename);
  $filenames=$filename;
  send_mail($filename.".zip",$email);
  unlink($filename);
}

function send_mail($filepath,$email)
{

$from = "Backup <f5craft.com/mac>";
$subject = "Database backup";
$message="This attachment contains the backup of your database.";
$separator = md5(time());

// carriage return type (we use a PHP end of line constant)
$eol = PHP_EOL;

// attachment name
$filename = "backup.zip";

//move_uploaded_file("/js/".$filename);

//$pdfdoc is PDF generated by FPDF
$attachment = chunk_split(base64_encode(file_get_contents($filepath)));

}
function compress($filepath)

     {

         $zip = new ZipArchive();
  $file=$filepath.".zip";
 if($zip->open($file,1?ZIPARCHIVE::OVERWRITE:ZIPARCHIVE::CREATE)===TRUE)
 {
   // Add the files to the .zip file
   $zip->addFile($filepath);

   // Closing the zip file
   $zip->close();
 }
     }  
	 
   function query($files){
		 
		 require_once("models/backup_mail_function.php");		 
	 mysql_query("INSERT INTO `backup` (`i`, `date_time`, `backup_name`, `backup_to`) VALUES (NULL, CURRENT_TIMESTAMP, '".$files."', '".$_SESSION['user_fulle_name']."')");
		   
	}	
  echo("<script>alert('Backup stored successfully');</script>");
 // echo("<script>window.location.href='backup.php';</script>");
	 ?>
	 
